---
driver:
  name: vagrant

provisioner:
  name: chef_zero
  # You may wish to disable always updating cookbooks in CI or other testing environments.
  # For example:
  #   always_update_cookbooks: <%= !ENV['CI'] %>
  always_update_cookbooks: true

verifier:
  name: inspec

platforms:
  - name: ubuntu-16.04
    driver:
      provider: vmware_workstation
  - name: centos-7.3
    driver:
      provider: vmware_workstation

suites:
  - name: default
    run_list:
      - recipe[chef-zerotier::install]
      - recipe[chef-zerotier::ohai_plugin]
    #verifier:
    #  inspec_tests:
    #    - test/smoke/install
    attributes:
      ohai:
        plugin_path: /tmp/kitchen/ohai/plugins

